CREATE TABLE `pt_project_member` (
  `id` int NOT NULL AUTO_INCREMENT,
  `pt_member_id` int NOT NULL,
  `project_id` bigint DEFAULT NULL,
  `user_id` int NOT NULL,
  `role` varchar(255) NOT NULL,
  `project_color` varchar(255) DEFAULT NULL,
  `favorite` tinyint(1) NOT NULL DEFAULT '0',
  `wants_comment_notification_emails` tinyint(1) NOT NULL DEFAULT '1',
  `will_receive_mention_notifications_or_emails` tinyint(1) NOT NULL DEFAULT '1',
  `person_id` int DEFAULT NULL,
  `person_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `person_email` varchar(255) NOT NULL,
  `person_initials` varchar(10) DEFAULT NULL,
  `person_username` varchar(255) DEFAULT NULL,
  `last_viewed_at` int DEFAULT NULL,
  `created_date` int NOT NULL,
  `updated_date` int NOT NULL,
  `user_email` varchar(100) DEFAULT NULL,
  `person_kind` varchar(255) DEFAULT NULL,
  `project_uid` varchar(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `created_at` varchar(45) DEFAULT NULL,
  `updated_at` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_project` (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1