CREATE TABLE `pt_story_activity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `story_id` int DEFAULT NULL,
  `guid` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `kind` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `project_version` int DEFAULT NULL,
  `message` varchar(300) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `changes` json DEFAULT NULL,
  `primary_resources` json DEFAULT NULL,
  `project_uid` varchar(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `performed_by` bigint DEFAULT NULL,
  `occurred_date` double DEFAULT NULL,
  `project_id` int DEFAULT NULL,
  `resource_count` int DEFAULT NULL,
  `changed_count` int DEFAULT NULL,
  `secondary_resources` json DEFAULT NULL,
  `highlight` text,
  `created_at` varchar(45) DEFAULT NULL,
  `updated_at` varchar(45) DEFAULT NULL,
  `created_date` double(13,3) DEFAULT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_project` (`project_id`,`story_id`,`guid`),
  KEY `idx_story` (`story_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1