CREATE TABLE `pt_story_bk` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `uid` varchar(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `belongs` varchar(45) DEFAULT NULL,
  `order_number` double(20,10) DEFAULT NULL,
  `pt_story_id` bigint DEFAULT NULL,
  `type` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `priority` int DEFAULT NULL,
  `estimate` int DEFAULT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `current_state` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `requested_by_id` bigint DEFAULT NULL,
  `deadline` varchar(45) DEFAULT NULL,
  `url` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `created_date` double DEFAULT NULL,
  `updated_date` double DEFAULT NULL,
  `owned_by_id` bigint DEFAULT NULL,
  `collection_id` bigint DEFAULT NULL,
  `status_migrated` tinyint DEFAULT '0',
  `position` int NOT NULL DEFAULT '0',
  `project_id` int DEFAULT NULL,
  `owner_ids` json DEFAULT NULL,
  `story_priority` varchar(100) DEFAULT NULL,
  `labels` json DEFAULT NULL,
  `follower_ids` json DEFAULT NULL,
  `accepted_at` varchar(45) DEFAULT NULL,
  `created_at` varchar(45) DEFAULT NULL,
  `updated_at` varchar(45) DEFAULT NULL,
  `total_comments` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_story` (`pt_story_id`,`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1