CREATE TABLE `collection_notification` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL COMMENT 'User id of member or owner collection',
  `email` varchar(225) NOT NULL,
  `collection_id` bigint NOT NULL DEFAULT '0',
  `object_uid` varbinary(1000) NOT NULL,
  `object_type` varbinary(50) NOT NULL,
  `action` int NOT NULL DEFAULT '0' COMMENT 'he action of the user changes the data of shared objects\n0: created (default )\n1: edited\n2: moved\n3: deleted\n4: completed (mark done) \n5: completed sub-task\n6: commented\n7: approved\n8: changed date\n9: changed time\n1:> changed location\n1:> rejected \n1:> started',
  `action_time` double(13,3) DEFAULT NULL,
  `read` tinyint(1) NOT NULL DEFAULT '0',
  `assignees` text NOT NULL,
  `content` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'content changes',
  `kanban_id` bigint NOT NULL DEFAULT '0',
  `kanban_card_id` bigint NOT NULL DEFAULT '0',
  `created_date` double(13,3) NOT NULL DEFAULT '0.000',
  `updated_date` double(13,3) NOT NULL DEFAULT '0.000',
  `comment_id` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_on_object_type_and_object_uid_and` (`object_uid`,`object_type`),
  KEY `idx_collection_id` (`collection_id`),
  KEY `idx_updated_date` (`updated_date`),
  KEY `idx_created_date` (`created_date`),
  KEY `idx_action` (`action`),
  KEY `idx_object_type` (`object_type`),
  KEY `idx_email` (`email`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1