CREATE TABLE `realtime_chat_channel_user_last_seen` (
  `id` int NOT NULL AUTO_INCREMENT,
  `email` varchar(100) NOT NULL,
  `channel_id` int NOT NULL DEFAULT '0',
  `channel_name` varchar(100) NOT NULL,
  `last_seen` double(13,3) NOT NULL,
  `last_message_uid` varchar(100) NOT NULL,
  `channel_last_message_uid` varchar(100) DEFAULT NULL,
  `unread` int NOT NULL DEFAULT '0',
  `remine` int DEFAULT NULL,
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) NOT NULL,
  `disabled` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `realtime_chat_channel_user_last_seen_UN` (`email`,`channel_name`),
  KEY `idx_last_msg_uid` (`last_message_uid`),
  KEY `idx_last_seen` (`last_seen`),
  KEY `idx_channel_name` (`channel_name`),
  KEY `idx_email` (`email`),
  KEY `idx_revoke` (`disabled`),
  KEY `idx_updated_date` (`updated_date`),
  KEY `idx_last_msg_uid_channel` (`channel_last_message_uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3