CREATE TABLE `helper_articles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `article_uid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Unique identifier for the article (UUID)',
  `title` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Article title',
  `alias` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'URL-friendly alias generated from title',
  `content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Article content (HTML or Markdown)',
  `ai_category` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'AI-suggested category from image/video analysis',
  `ai_platform` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'AI-suggested platform from image/video analysis',
  `platform` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Platform manually selected by user (Web, Mobile, Desktop, etc.)',
  `approved` tinyint(1) DEFAULT '0' COMMENT 'Whether the article is approved',
  `approved_by` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'User who approved the article',
  `approved_at` timestamp NULL DEFAULT NULL COMMENT 'Approval timestamp',
  `created_by` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'User who created the article',
  `article_type` enum('regular','system') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'regular' COMMENT 'Type of article',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Article creation timestamp',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Article last update timestamp',
  PRIMARY KEY (`id`),
  UNIQUE KEY `article_uid` (`article_uid`),
  KEY `idx_ai_category` (`ai_category`) USING BTREE,
  KEY `idx_ai_platform` (`ai_platform`) USING BTREE,
  KEY `idx_alias` (`alias`) USING BTREE,
  KEY `idx_approved` (`approved`) USING BTREE,
  KEY `idx_article_type` (`article_type`) USING BTREE,
  KEY `idx_article_uid` (`article_uid`) USING BTREE,
  KEY `idx_created_at` (`created_at`) USING BTREE,
  KEY `idx_created_by` (`created_by`) USING BTREE,
  KEY `idx_platform` (`platform`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Articles table (primary data store)'