CREATE TABLE `apple_webhook_events` (
  `id` int NOT NULL AUTO_INCREMENT,
  `request_id` varchar(255) NOT NULL,
  `timestamp` varchar(255) NOT NULL,
  `method` varchar(10) NOT NULL,
  `path` varchar(500) NOT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `processed` tinyint(1) DEFAULT '1',
  `notification_type` varchar(100) NOT NULL,
  `notification_uuid` varchar(255) NOT NULL,
  `subtype` varchar(100) DEFAULT NULL,
  `environment` varchar(50) NOT NULL,
  `signed_date` varchar(255) NOT NULL,
  `app_metadata` json DEFAULT NULL,
  `renewal_info` json DEFAULT NULL,
  `transaction_info` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_request_id` (`request_id`),
  KEY `idx_notification_uuid` (`notification_uuid`),
  KEY `idx_notification_type` (`notification_type`),
  KEY `idx_environment` (`environment`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_method` (`method`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1