CREATE TABLE `collection_instance_member` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL COMMENT 'user_id of member',
  `owner_user_id` bigint unsigned NOT NULL COMMENT 'user_id of owner',
  `collection_id` bigint unsigned NOT NULL COMMENT 'ID record of table collection - shared by the owner ',
  `color` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `favorite` tinyint unsigned NOT NULL DEFAULT '0',
  `is_hide` tinyint unsigned NOT NULL DEFAULT '0',
  `recent_time` double(13,3) NOT NULL DEFAULT '0.000',
  `created_date` double(13,3) NOT NULL DEFAULT '0.000',
  `updated_date` double(13,3) NOT NULL DEFAULT '0.000',
  `root_id` bigint DEFAULT NULL,
  `archive_status` tinyint(1) DEFAULT '0',
  `show_archive_sub_col` tinyint(1) NOT NULL DEFAULT '1',
  `archived_time` double(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_owner_user_id` (`owner_user_id`),
  KEY `idx_collection_id` (`collection_id`),
  KEY `idx_updated_date` (`updated_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1