CREATE TABLE `collection_shared_member` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `collection_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'ID record of the collection table',
  `calendar_uri` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'This is shared calendar for member, each member will be shared one calendar, it will contain calendar uri of table [calendarinstance] of sabreDAV',
  `access` tinyint NOT NULL DEFAULT '2' COMMENT 'This is permission shared collection.\n OWNER = 0\n  READ = 1\n  READ_WRITE = 2',
  `shared_status` tinyint NOT NULL DEFAULT '0' COMMENT 'The status of the shared collection,\n\n WAITING = 0,\n  JOINED = 1,\n  DECLINED = 2,\n  REMOVED = 3, // remove by owner, un-share\n  LEAVED = 4, // leave share (member leave)\n  TEMP_REMOVE = -1 // worker mark it remove after 1 hour',
  `shared_email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'This contains the Flo email address who shared collection by owner',
  `member_user_id` bigint unsigned NOT NULL,
  `contact_uid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'It will contain the contact uid. Purpose >> the client app can load quickly the contact to show on the UI',
  `contact_href` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'It is href of the contact, address book',
  `account_id` bigint unsigned DEFAULT '0' COMMENT 'This is third party account setting ID, it support for the contact of third party account. Default value = 0 (Flo account)',
  `created_date` double(13,3) NOT NULL DEFAULT '0.000',
  `updated_date` double(13,3) NOT NULL DEFAULT '0.000',
  `joined_date` double(13,3) NOT NULL DEFAULT '0.000',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_collection_id` (`collection_id`),
  KEY `idx_shared_status` (`shared_status`) USING BTREE,
  KEY `idx_updated_date` (`updated_date`) USING BTREE,
  KEY `idx_member_user_status_access_id` (`member_user_id`,`shared_status`,`access`),
  KEY `idx_user_collection_member` (`user_id`,`collection_id`,`shared_email`),
  KEY `idx_collection_shared_status` (`collection_id`,`shared_status`),
  KEY `idx_access` (`access`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1