CREATE TABLE `user_notification` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL COMMENT 'User id of member or owner collection',
  `collection_notification_id` bigint NOT NULL DEFAULT '0',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '0: Un-read\n\n1: Read\n\n2: Closed',
  `has_mention` tinyint(1) NOT NULL DEFAULT '0',
  `alert_duration` int DEFAULT '0',
  `created_date` double(13,3) NOT NULL DEFAULT '0.000',
  `updated_date` double(13,3) NOT NULL DEFAULT '0.000',
  `action_time` double(13,3) NOT NULL DEFAULT '0.000',
  `deleted_date` double(13,3) DEFAULT NULL,
  `counted` tinyint(1) NOT NULL DEFAULT '0',
  `is_active` tinyint(1) GENERATED ALWAYS AS (if((`deleted_date` is null),1,0)) VIRTUAL COMMENT '1: active, 0: deleted',
  `cnm_id` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_notification_id` (`collection_notification_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_deleted_date` (`deleted_date`),
  KEY `idx_updated_date` (`updated_date`),
  KEY `idx_status` (`status`),
  KEY `idx_mention` (`has_mention`),
  KEY `idx_un_query` (`user_id`,`status`,`created_date`,`collection_notification_id`),
  KEY `idx_is_active` (`is_active`),
  KEY `index_for_case_not_exist_modifiled` (`user_id`,`is_active`,`created_date`) USING BTREE,
  KEY `comp_idx_user_notifications` (`collection_notification_id`,`user_id`,`updated_date`,`is_active`) USING BTREE,
  KEY `idx_un_user_active_updated` (`user_id`,`is_active`,`updated_date`) USING BTREE,
  KEY `idx_un_cover` (`user_id`,`is_active`,`updated_date`,`collection_notification_id`,`has_mention`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1