CREATE TABLE `transactions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `gateway_id` bigint NOT NULL DEFAULT '0',
  `original_transaction_uid` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `transaction_uid` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `receipt_data` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `amount` bigint NOT NULL DEFAULT '0',
  `type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'initial_purchase, renewal, refund, etc.',
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'USD',
  `notification_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `subtype` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `order_info` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `order_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `gateway_trans_id` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `result_code` int NOT NULL DEFAULT '0' COMMENT '0:success, !=0:error',
  `message` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `pay_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'app',
  `response_time` timestamp NOT NULL,
  `extra_data` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `signature` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `created_date` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_year` int GENERATED ALWAYS AS (year(`created_date`)) STORED NOT NULL,
  `updated_date` timestamp(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `uniq_key_sha` char(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (sha2(concat_ws(_utf8mb4'|',`original_transaction_uid`,`transaction_uid`,`notification_type`,`subtype`),256)) STORED,
  `uniq_transaction` tinyint GENERATED ALWAYS AS ((case when ((`notification_type` = _utf8mb4'SUBSCRIBED') or ((`notification_type` = _utf8mb4'DID_CHANGE_RENEWAL_PREF') and (`subtype` = _utf8mb4'UPGRADE'))) then 1 else NULL end)) STORED,
  PRIMARY KEY (`id`,`created_year`),
  UNIQUE KEY `uniq_with_sha` (`created_year`,`uniq_key_sha`,`uniq_transaction`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_gateway_id` (`gateway_id`),
  KEY `idx_transaction_uid` (`transaction_uid`),
  KEY `idx_result_code` (`result_code`),
  KEY `idx_created_date` (`created_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
/*!50100 PARTITION BY RANGE (`created_year`)
(PARTITION p2024 VALUES LESS THAN (2025) ENGINE = InnoDB,
 PARTITION p2025 VALUES LESS THAN (2026) ENGINE = InnoDB,
 PARTITION p2026 VALUES LESS THAN (2027) ENGINE = InnoDB,
 PARTITION p2027 VALUES LESS THAN (2028) ENGINE = InnoDB,
 PARTITION p2028 VALUES LESS THAN (2029) ENGINE = InnoDB,
 PARTITION p2029 VALUES LESS THAN (2030) ENGINE = InnoDB,
 PARTITION p2030 VALUES LESS THAN (2031) ENGINE = InnoDB,
 PARTITION pmax VALUES LESS THAN MAXVALUE ENGINE = InnoDB) */