CREATE TABLE `usages` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `component_id` bigint NOT NULL DEFAULT '0',
  `used_value` bigint NOT NULL DEFAULT '0',
  `used_data` json DEFAULT NULL,
  `collection_id` bigint DEFAULT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `todo_bytes` bigint NOT NULL DEFAULT '0',
  `note_bytes` bigint NOT NULL DEFAULT '0',
  `event_bytes` bigint NOT NULL DEFAULT '0',
  `cal_bytes` bigint NOT NULL DEFAULT '0',
  `card_bytes` bigint NOT NULL DEFAULT '0',
  `file_comment_bytes` bigint NOT NULL DEFAULT '0',
  `file_chat_bytes` bigint NOT NULL DEFAULT '0',
  `file_note_bytes` bigint NOT NULL DEFAULT '0',
  `mail_bytes` bigint NOT NULL DEFAULT '0',
  `file_contact_bytes` bigint NOT NULL DEFAULT '0',
  `qa_bytes` bigint NOT NULL DEFAULT '0' COMMENT 'Test only',
  `is_active` tinyint NOT NULL DEFAULT '1',
  `created_date` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_date` timestamp(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_year` int GENERATED ALWAYS AS (year(`created_date`)) STORED NOT NULL,
  `note_count` bigint DEFAULT NULL COMMENT 'Count of VJOURNAL (calendar note) objects. Source: FloDAV calendar service',
  `file_note_count` bigint DEFAULT NULL COMMENT 'Count of file attachment (note) objects. Source: FloAPINodeJS file attachment service',
  `file_chat_count` bigint DEFAULT NULL COMMENT 'Count of chat file uploads. Source: FloMedia chat upload service',
  `file_comment_count` bigint DEFAULT NULL COMMENT 'Count of collection comment file uploads. Source: FloMedia file-comment service',
  `email_count` bigint DEFAULT NULL COMMENT 'Count of EMAIL objects. Source: TBD (placeholder)',
  `todo_count` bigint DEFAULT NULL COMMENT 'Count of VTODO (calendar task) objects. Source: FloDAV calendar service',
  `event_count` bigint DEFAULT NULL COMMENT 'Count of VEVENT (calendar event) objects. Source: FloDAV calendar service',
  `card_count` bigint DEFAULT NULL COMMENT 'Count of VCARD (contact) objects. Source: FloDAV card service',
  PRIMARY KEY (`id`,`created_year`),
  KEY `idx_user_component` (`user_id`,`component_id`),
  KEY `idx_created_date` (`created_date`),
  KEY `idx_component_active_user` (`component_id`,`is_active`,`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
/*!50100 PARTITION BY RANGE (`created_year`)
(PARTITION p2024 VALUES LESS THAN (2025) ENGINE = InnoDB,
 PARTITION p2025 VALUES LESS THAN (2026) ENGINE = InnoDB,
 PARTITION p2026 VALUES LESS THAN (2027) ENGINE = InnoDB,
 PARTITION p2027 VALUES LESS THAN (2028) ENGINE = InnoDB,
 PARTITION p2028 VALUES LESS THAN (2029) ENGINE = InnoDB,
 PARTITION p2029 VALUES LESS THAN (2030) ENGINE = InnoDB,
 PARTITION p2030 VALUES LESS THAN (2031) ENGINE = InnoDB,
 PARTITION pmax VALUES LESS THAN MAXVALUE ENGINE = InnoDB) */