CREATE TABLE `collection` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `calendar_uri` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `parent_id` bigint NOT NULL DEFAULT '0',
  `root_id` bigint NOT NULL DEFAULT '0',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `channel_id` bigint DEFAULT NULL,
  `realtime_channel` varchar(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT '',
  `color` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `type` tinyint(1) NOT NULL DEFAULT '0',
  `kind` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1 - normal\n2 - epic',
  `info_card_order` int NOT NULL DEFAULT '0',
  `current_mode` int NOT NULL DEFAULT '0',
  `alerts` json DEFAULT NULL,
  `order_storyboard` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `order_kanban` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `state` tinyint unsigned DEFAULT '1',
  `flag` tinyint unsigned NOT NULL DEFAULT '0',
  `is_hide` tinyint unsigned NOT NULL DEFAULT '0',
  `is_expand` tinyint unsigned NOT NULL DEFAULT '0',
  `view_mode` tinyint unsigned NOT NULL DEFAULT '0',
  `view_sort` tinyint unsigned NOT NULL DEFAULT '0',
  `kanban_mode` tinyint(1) DEFAULT '0',
  `icon` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '',
  `due_date` double(13,3) DEFAULT '0.000',
  `recent_time` double(13,3) NOT NULL DEFAULT '0.000',
  `is_trashed` tinyint unsigned NOT NULL DEFAULT '0',
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  `pt_project_id` int DEFAULT NULL,
  `description` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `idx_channel_id` (`channel_id`),
  KEY `idx_is_trashed` (`is_trashed`) USING BTREE,
  KEY `idx_user_id` (`user_id`) USING BTREE,
  KEY `idx_calendar_id` (`calendar_uri`) USING BTREE,
  KEY `idx_on_user_id_and_parent_id` (`user_id`,`parent_id`) USING BTREE,
  KEY `idx_on_id_and_user_id` (`id`,`user_id`) USING BTREE,
  KEY `idx_type` (`type`) USING BTREE,
  KEY `idx_root_id` (`root_id`),
  KEY `idx_relative_and_trash` (`user_id`,`root_id`,`parent_id`,`is_trashed`),
  KEY `idx_pt_project` (`pt_project_id`),
  KEY `idx_trash_type` (`type`,`is_trashed`),
  KEY `idx_user_id_and_type` (`user_id`,`type`),
  FULLTEXT KEY `idx_collection_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='utf8_unicode_ci'