CREATE TABLE `pt_project` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `pt_project_id` bigint DEFAULT NULL,
  `status` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `version` int DEFAULT NULL,
  `iteration_length` int DEFAULT NULL,
  `week_start_day` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `point_scale` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `point_scale_is_custom` tinyint(1) DEFAULT NULL,
  `bugs_and_chores_are_estimateble` tinyint(1) DEFAULT NULL,
  `automatic_planning` tinyint(1) DEFAULT NULL,
  `enable_task` tinyint(1) DEFAULT NULL,
  `time_zone` int DEFAULT NULL,
  `velocity_averaged_over` int DEFAULT NULL,
  `number_of_done_iterations_to_show` int DEFAULT NULL,
  `has_google_domain` tinyint(1) DEFAULT NULL,
  `description` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `enable_incoming_emails` tinyint(1) DEFAULT NULL,
  `initial_velocity` int DEFAULT NULL,
  `public` tinyint(1) DEFAULT NULL,
  `atom_enabled` tinyint(1) DEFAULT NULL,
  `project_type` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `start_date` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `start_time` double DEFAULT NULL,
  `created_date` double DEFAULT NULL,
  `updated_date` double DEFAULT NULL,
  `show_story_priority` tinyint(1) DEFAULT NULL,
  `show_priority_icon_in_all_panels` tinyint(1) DEFAULT NULL,
  `current_interation_number` int DEFAULT NULL,
  `collection_id` bigint DEFAULT NULL,
  `uid` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci