CREATE TABLE `setting` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `default_cal` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  `timezone` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'America/Chicago',
  `tz_city` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `working_time` json NOT NULL,
  `event_duration` int NOT NULL DEFAULT '0',
  `alert_default` int NOT NULL DEFAULT '0',
  `snooze_default` int NOT NULL DEFAULT '15',
  `timezone_support` tinyint NOT NULL DEFAULT '0',
  `task_duration` int NOT NULL DEFAULT '0',
  `deadline` int NOT NULL DEFAULT '0',
  `due_task` int NOT NULL DEFAULT '0',
  `number_stask` int NOT NULL DEFAULT '0',
  `total_duration` int NOT NULL DEFAULT '0',
  `buffer_time` int NOT NULL DEFAULT '0',
  `hide_stask` tinyint NOT NULL DEFAULT '0',
  `background` int NOT NULL DEFAULT '0',
  `short_duration` int NOT NULL DEFAULT '30',
  `medium_duration` int NOT NULL DEFAULT '60',
  `long_duration` int NOT NULL DEFAULT '180',
  `default_folder` bigint unsigned NOT NULL DEFAULT '0',
  `calendar_color` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  `folder_color` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  `navbar_system` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `navbar_custom` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `infobox` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `infobox_order` json NOT NULL,
  `contact_display_name` int NOT NULL DEFAULT '0',
  `contact_display_inlist` int NOT NULL DEFAULT '0',
  `m_ade` tinyint NOT NULL DEFAULT '1',
  `m_event` tinyint NOT NULL DEFAULT '1',
  `m_task` tinyint NOT NULL DEFAULT '1',
  `m_stask` tinyint NOT NULL DEFAULT '1',
  `m_done_task` tinyint NOT NULL DEFAULT '1',
  `m_due_task` tinyint NOT NULL DEFAULT '1',
  `m_note` tinyint NOT NULL DEFAULT '1',
  `dw_due_task` tinyint NOT NULL DEFAULT '1',
  `dw_ade` tinyint NOT NULL DEFAULT '1',
  `dw_done_task` tinyint NOT NULL DEFAULT '1',
  `dw_note` tinyint NOT NULL DEFAULT '1',
  `del_warning` tinyint NOT NULL DEFAULT '1',
  `hide_future_task` tinyint NOT NULL DEFAULT '0',
  `ics_attachment` tinyint NOT NULL DEFAULT '1',
  `mail_auto_download_check` int NOT NULL DEFAULT '0',
  `mail_num_time_dont_auto_download` int NOT NULL DEFAULT '6',
  `mail_time_dont_auto_download` int NOT NULL DEFAULT '1',
  `mail_display_act_button` int NOT NULL DEFAULT '0',
  `number_mail_lines_preview` int NOT NULL DEFAULT '4',
  `mail_moving_check` int NOT NULL DEFAULT '1',
  `mail_size_dont_download` int NOT NULL DEFAULT '10',
  `show_nutshell` tinyint NOT NULL DEFAULT '1',
  `show_bg_by_weather` tinyint NOT NULL DEFAULT '0',
  `week_start` int NOT NULL DEFAULT '0',
  `send_and_track` int NOT NULL DEFAULT '2',
  `action_icon` int NOT NULL DEFAULT '0',
  `emailbox_order` json NOT NULL,
  `alert_before` int NOT NULL DEFAULT '60',
  `send_invite` tinyint NOT NULL DEFAULT '0',
  `from_email` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  `default_alert_ade` int DEFAULT '0',
  `default_alert_todo` int DEFAULT '0',
  `default_milestone_alert` int DEFAULT '0',
  `avatar` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `assign_tz_eve` tinyint NOT NULL DEFAULT '1',
  `m_show` int NOT NULL DEFAULT '23',
  `dw_show` int NOT NULL DEFAULT '23',
  `agenda_show` int NOT NULL DEFAULT '23',
  `move_email` int NOT NULL DEFAULT '1',
  `noti_bear_track` int NOT NULL DEFAULT '0',
  `state` int NOT NULL DEFAULT '0',
  `recent_tz` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `order_url` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `order_todo` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `keep_state` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `omni_cal_id` varchar(500) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  `url_option` int NOT NULL DEFAULT '0',
  `init_planner_st` int NOT NULL DEFAULT '0',
  `order_storyboard` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `show_star` int NOT NULL DEFAULT '0',
  `signature` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `filing_email` int DEFAULT '0',
  `show_date_timezone` tinyint DEFAULT '0',
  `show_feedback` tinyint DEFAULT '1',
  `theme_mode` tinyint NOT NULL DEFAULT '0' COMMENT '0 (light - default), = 1: dark',
  `scroll_24h` tinyint unsigned NOT NULL DEFAULT '1' COMMENT 'Enable "Working Hour" mode',
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  `hide_done_todo` tinyint(1) NOT NULL DEFAULT '1',
  `indicate_done_todo` tinyint(1) NOT NULL DEFAULT '0',
  `note_ask` tinyint(1) NOT NULL DEFAULT '0',
  `todo_ask` tinyint(1) NOT NULL DEFAULT '0',
  `note_collection_id` bigint unsigned NOT NULL DEFAULT '0',
  `todo_collection_id` bigint unsigned NOT NULL DEFAULT '0',
  `notification_clean_date` int NOT NULL DEFAULT '2592000' COMMENT 'DEFAULT: 43200 = 1 MONTH IN SECOND',
  `clean_after_opening` tinyint(1) NOT NULL DEFAULT '1',
  `todo_move_mail_noti` tinyint NOT NULL DEFAULT '1',
  `event_move_mail_noti` tinyint NOT NULL DEFAULT '1',
  `incoming_call` tinyint DEFAULT '1',
  `incoming_mail` tinyint DEFAULT '1',
  `filter_chat` tinyint DEFAULT '1',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_user_id` (`user_id`) USING BTREE,
  KEY `idx_notification_clean_date` (`notification_clean_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='utf8_unicode_ci'