CREATE TABLE `storage_file` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `uid` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `path` varchar(4000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `path_hash` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `parent_uid` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `name` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `size` bigint DEFAULT NULL,
  `mtime` bigint DEFAULT NULL,
  `encrypted` tinyint(1) DEFAULT NULL,
  `unencrypted_size` bigint DEFAULT NULL,
  `etag` varchar(40) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `checksum` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `mimetype` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `owner` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `is_linked` tinyint(1) NOT NULL DEFAULT '0',
  `created_date` double DEFAULT NULL,
  `updated_date` double DEFAULT NULL,
  `deleted_date` double DEFAULT NULL,
  `is_shared` tinyint(1) NOT NULL DEFAULT '0',
  `has_cache` tinyint(1) NOT NULL DEFAULT '0',
  `has_thumbnail` tinyint(1) NOT NULL DEFAULT '0',
  `thumb_size` bigint DEFAULT NULL,
  `comp_size` bigint DEFAULT NULL,
  `is_available` tinyint DEFAULT NULL,
  `is_trashed` tinyint DEFAULT '0',
  `collection` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `created_by` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `is_private` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `storage_file_uid_IDX` (`uid`) USING BTREE,
  KEY `storage_file_collection_IDX` (`collection`) USING BTREE,
  KEY `storage_file_is_shared_IDX` (`is_shared`) USING BTREE,
  KEY `storage_file_owner_idx` (`owner`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci