CREATE TABLE `third_party_account` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `server_income` varchar(255) NOT NULL DEFAULT '',
  `user_income` varchar(255) NOT NULL DEFAULT '',
  `pass_income` varchar(1000) NOT NULL DEFAULT '',
  `port_income` varchar(255) NOT NULL DEFAULT '',
  `use_ssl_income` int DEFAULT '0',
  `type_income` int DEFAULT '0',
  `server_smtp` varchar(255) DEFAULT '',
  `user_smtp` varchar(255) DEFAULT '',
  `pass_smtp` varchar(1000) DEFAULT '',
  `port_smtp` varchar(255) DEFAULT '',
  `use_ssl_smtp` int NOT NULL DEFAULT '0',
  `auth_type_smtp` int NOT NULL DEFAULT '0',
  `server_caldav` varchar(255) DEFAULT '',
  `server_path_caldav` varchar(255) DEFAULT '',
  `port_caldav` varchar(255) DEFAULT '',
  `use_ssl_caldav` int DEFAULT '0',
  `use_kerberos_caldav` int DEFAULT '0',
  `auth_type` int DEFAULT '0',
  `account_type` int DEFAULT '0',
  `account_sync` json DEFAULT NULL,
  `auth_key` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `auth_token` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `full_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
  `refresh_token` text NOT NULL,
  `provider` varchar(255) DEFAULT '',
  `icloud_user_id` varchar(255) NOT NULL DEFAULT '',
  `third_party_user_id` varchar(255) NOT NULL DEFAULT '',
  `user_caldav` varchar(255) NOT NULL DEFAULT '',
  `email_address` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `token_expire` int DEFAULT '0',
  `activated_push` int NOT NULL DEFAULT '0',
  `signature` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_on_user_id_and_user_income_and_account_type` (`user_id`,`user_income`,`account_type`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='utf8_unicode_ci'