CREATE TABLE `card_contact` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `uid` varbinary(1000) DEFAULT NULL,
  `addressbookid` int NOT NULL,
  `card_id` int unsigned DEFAULT NULL,
  `uri` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `first_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `midle_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email_address` json DEFAULT NULL,
  `company` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact_avatar` text COLLATE utf8mb4_unicode_ci,
  `phone` json DEFAULT NULL,
  `skype_call` json DEFAULT NULL,
  `skype_chat` json DEFAULT NULL,
  `vip` tinyint unsigned DEFAULT '0',
  `is_group` tinyint unsigned DEFAULT '0',
  `trashed` tinyint(1) DEFAULT '0',
  `email_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `unique_idx_card_contact_uid_addressbookid` (`uid`,`addressbookid`) USING BTREE,
  KEY `idx_is_trashed` (`trashed`) USING BTREE,
  KEY `idx_cardcontact_uid` (`uid`) USING BTREE,
  KEY `idx_cardcontact_addressbookid_uri` (`addressbookid`,`uri`) USING BTREE,
  KEY `fk_card_contact_uid_addressbookid` (`card_id`) USING BTREE,
  FULLTEXT KEY `card_contact_email_text_IDX` (`email_text`),
  CONSTRAINT `fk_card_contact_uid_addressbookid` FOREIGN KEY (`card_id`) REFERENCES `cards` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC