CREATE TABLE `collection_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `collection_activity_id` bigint NOT NULL DEFAULT '0',
  `email` varchar(255) NOT NULL DEFAULT '',
  `action` int NOT NULL DEFAULT '0' COMMENT 'he action of the user changes the data of shared objects\n0: created (default )\n1: edited\n2: moved\n3: deleted\n4: completed (mark done) \n5: completed sub-task\n6: commented\n7: approved\n8: changed date\n9: changed time\n1:> changed location\n1:> rejected \n1:> started',
  `action_time` double(13,3) NOT NULL DEFAULT '0.000',
  `assignees` text NOT NULL,
  `content` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'content changes',
  `tag_name` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  `kanban_id` bigint NOT NULL DEFAULT '0',
  `kanban_card_id` bigint NOT NULL DEFAULT '0',
  `created_date` double(13,3) NOT NULL DEFAULT '0.000',
  `updated_date` double(13,3) NOT NULL DEFAULT '0.000',
  `category` tinyint(1) NOT NULL DEFAULT '0',
  `collection_id` bigint NOT NULL DEFAULT '-1',
  PRIMARY KEY (`id`),
  KEY `idx_activity_id` (`collection_activity_id`),
  KEY `idx_email` (`email`),
  KEY `idx_updated_date` (`updated_date`),
  KEY `collection_history_collection_id_IDX` (`collection_id`) USING BTREE,
  KEY `collection_history_collection_id_updated_date_IDX` (`collection_id`,`updated_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1