CREATE TABLE `collection_comment` (
  `id` int NOT NULL AUTO_INCREMENT,
  `collection_activity_id` bigint NOT NULL DEFAULT '0',
  `user_id` bigint NOT NULL,
  `email` varchar(255) NOT NULL DEFAULT '',
  `action` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'value = 0 >> created (default)\nvalue = 1 >> edited',
  `action_time` double(13,3) NOT NULL DEFAULT '0.000',
  `upload_time` double(13,3) NOT NULL DEFAULT '0.000',
  `comment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `parent_id` bigint NOT NULL DEFAULT '0',
  `reaction_time` double(13,3) NOT NULL DEFAULT '0.000',
  `created_date` double(13,3) NOT NULL DEFAULT '0.000',
  `updated_date` double(13,3) NOT NULL DEFAULT '0.000',
  `pt_comment_id` bigint NOT NULL DEFAULT '0',
  `mention_all` tinyint(1) NOT NULL DEFAULT '0',
  `collection_id` bigint NOT NULL DEFAULT '-1',
  `comment_marked` json DEFAULT (json_object()) COMMENT 'The data of the comment has been quoted at the time it was quoted.',
  `content_marked` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT 'All or part of the content of the original comment that the user has quoted.',
  `linked_object_time` double(13,3) NOT NULL DEFAULT '0.000',
  `is_draft` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_activity_id` (`collection_activity_id`),
  KEY `idx_updated_date` (`updated_date`),
  KEY `idx_email` (`email`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_created_date` (`created_date`),
  KEY `idx_collection_id` (`collection_id`),
  KEY `collection_comment_user_id_IDX` (`user_id`,`collection_id`,`updated_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1