CREATE TABLE `collection_notification_member_bk` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `channel_id` bigint NOT NULL DEFAULT '0',
  `collection_id` bigint NOT NULL DEFAULT '0',
  `calendarid` int NOT NULL DEFAULT '0',
  `member_user_id` bigint unsigned NOT NULL,
  `member_email` varchar(100) DEFAULT NULL,
  `access` tinyint(1) NOT NULL DEFAULT '2',
  `member_calendar_uri` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `owner_calendar_uri` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `owner_user_id` bigint DEFAULT NULL,
  `owner_email` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `fk_collection_id` bigint unsigned DEFAULT NULL,
  `fk_channel_id` bigint DEFAULT NULL,
  `fk_cm_id` bigint unsigned DEFAULT NULL,
  `fk_csm_id` bigint unsigned DEFAULT NULL,
  `last_seen_chat` double(13,3) NOT NULL DEFAULT '0.000',
  `last_seen_call` double(13,3) NOT NULL DEFAULT '0.000',
  `created_date` double(13,3) DEFAULT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '0',
  `partition_group` tinyint GENERATED ALWAYS AS ((case when ((`collection_id` > 0) and (`channel_id` > 0)) then 1 when ((`collection_id` = 0) and (`channel_id` > 0)) then 2 else 3 end)) STORED NOT NULL,
  PRIMARY KEY (`id`,`partition_group`) USING BTREE,
  UNIQUE KEY `unq_user_collection_channel` (`member_user_id`,`collection_id`,`channel_id`,`partition_group`) USING BTREE,
  KEY `comp_collection_channel` (`collection_id`,`channel_id`),
  KEY `idx_user_id` (`member_user_id`),
  KEY `idx_collection_id` (`collection_id`),
  KEY `idx_channel_id` (`channel_id`),
  KEY `idx_user_email` (`member_email`),
  KEY `collection_notification_member_member_user_id_IDX` (`member_user_id`,`partition_group`) USING BTREE,
  KEY `idx_access` (`access`),
  KEY `idx_cnm_active_access` (`member_user_id`,`is_active`,`access`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1