CREATE TABLE `conference_member` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `last_history_id` bigint NOT NULL DEFAULT '0',
  `user_id` bigint unsigned NOT NULL,
  `channel_id` bigint unsigned NOT NULL,
  `uid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `email` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone_number` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `is_creator` tinyint unsigned NOT NULL DEFAULT '0',
  `title` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `avatar` text COLLATE utf8mb4_unicode_ci,
  `vip` tinyint(1) NOT NULL DEFAULT '0',
  `star_time` double(13,3) NOT NULL DEFAULT '0.000',
  `chat_url` varchar(2000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `member_arn` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_date` double(13,3) NOT NULL DEFAULT '0.000',
  `created_date` double(13,3) NOT NULL DEFAULT '0.000',
  `revoke_time` double(13,3) NOT NULL DEFAULT '0.000',
  `join_time` double(13,3) DEFAULT '0.000',
  `view_chat_history` tinyint(1) NOT NULL DEFAULT '1',
  `last_seen_call` double(13,3) NOT NULL DEFAULT '0.000',
  `meeting_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'The last seen meeting id',
  `last_missed_call` double(13,3) NOT NULL,
  `missed_calls` int NOT NULL DEFAULT '0',
  `notification_chat` tinyint(1) NOT NULL DEFAULT '2',
  `notification_call` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_on_conference_id_and_user_id_and_phone` (`channel_id`,`phone_number`),
  UNIQUE KEY `uniq_on_conference_id_and_user_id_and_user_name` (`user_id`,`email`,`channel_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_channel_id` (`channel_id`) USING BTREE,
  KEY `idx_revoke_time` (`revoke_time`) USING BTREE,
  KEY `idx_updated_date` (`updated_date`) USING BTREE,
  KEY `idx_email` (`email`),
  KEY `idx_vip` (`vip`),
  KEY `comp_creator` (`id`,`email`,`is_creator`,`revoke_time`),
  KEY `idx_last_history_id` (`last_history_id`),
  KEY `idx_user_id_and_revoke_time_and_channel_id` (`user_id`,`revoke_time`,`channel_id`),
  KEY `idx_conference_member_vip` (`user_id`,`vip`,`revoke_time`,`channel_id`),
  KEY `idx_conference_member_sort` (`user_id`,`channel_id`,`id`,`updated_date`,`created_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='utf8mb4_unicode_ci'