CREATE TABLE `contact_history` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `source_object_uid` varbinary(1000) NOT NULL,
  `source_object_type` varbinary(50) NOT NULL,
  `source_account_id` bigint unsigned DEFAULT '0',
  `source_object_href` text COLLATE utf8mb4_general_ci,
  `destination_object_uid` varbinary(1000) NOT NULL,
  `destination_object_type` varbinary(50) NOT NULL,
  `destination_account_id` bigint unsigned DEFAULT '0',
  `destination_object_href` text COLLATE utf8mb4_general_ci,
  `action` tinyint NOT NULL DEFAULT '0',
  `action_data` text COLLATE utf8mb4_general_ci,
  `path` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT '',
  `is_trashed` tinyint unsigned NOT NULL DEFAULT '0',
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_user_id` (`user_id`) USING BTREE,
  KEY `idx_on_source` (`user_id`,`source_object_uid`,`source_object_type`,`source_account_id`),
  KEY `idx_on_destination` (`user_id`,`destination_object_type`,`destination_object_uid`,`destination_account_id`),
  KEY `idx_on_updated_date` (`updated_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='utf8_unicode_ci'