CREATE TABLE `realtime_message` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL DEFAULT '0',
  `uid` varchar(300) NOT NULL,
  `code` varchar(100) NOT NULL,
  `from` varchar(100) NOT NULL,
  `type` enum('NOTIFICATION','EVENT','CHAT') NOT NULL,
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'because have not function search messaege , so I design it json format',
  `metadata` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'because have not function search messaege , so I design it json format',
  `send_type` enum('CHANNEL','USER','BROADCAST') NOT NULL,
  `to_channel` varchar(300) DEFAULT NULL COMMENT 'channel name',
  `parent_uid` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `qos` tinyint NOT NULL DEFAULT '0' COMMENT '0: only send 1 time, 1: alway send unit user readed',
  `delay` int NOT NULL DEFAULT '0' COMMENT 'time second delay send',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '1: sent; 0: unsend',
  `sent_time` double(13,3) DEFAULT NULL,
  `reaction_time` double(13,3) NOT NULL DEFAULT '0.000',
  `created_date` double(13,3) NOT NULL,
  `updated_date` double(13,3) NOT NULL,
  `deleted_date` double(13,3) DEFAULT NULL,
  `content_marked` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `message_marked` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `reply_number` int NOT NULL DEFAULT '0',
  `mention_emails` text,
  `migrate_to_es` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_message_type` varchar(45) DEFAULT NULL,
  `linked_object_time` double(13,3) NOT NULL DEFAULT '0.000',
  `is_pending` tinyint DEFAULT NULL COMMENT 'NULL=not pending/completed, 1=pending file upload',
  PRIMARY KEY (`id`),
  UNIQUE KEY `notification_UN` (`uid`),
  KEY `realtime_message_created_date_IDX` (`created_date`) USING BTREE,
  KEY `realtime_message_to_channel_IDX` (`to_channel`) USING BTREE,
  KEY `realtime_message_parent_uid_IDX` (`parent_uid`) USING BTREE,
  KEY `realtime_message_status_IDX` (`status`) USING BTREE,
  KEY `idx_type` (`type`),
  KEY `realtime_message_type_IDX` (`type`) USING BTREE /*!80000 INVISIBLE */,
  KEY `idx_to_channel_and_created_date` (`to_channel`,`created_date`),
  KEY `idx_reaction_time` (`reaction_time`),
  KEY `idx_updated_date` (`updated_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1