CREATE TABLE `purchases` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `order_id` bigint NOT NULL DEFAULT '0',
  `description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `transaction_id` bigint NOT NULL DEFAULT '0',
  `is_current` tinyint(1) NOT NULL DEFAULT '0',
  `purchase_platform` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Allow admin set instead buy',
  `product_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` tinyint(1) NOT NULL COMMENT '0:cancelled, 1:active, 2:grace_period, 3:expired',
  `purchase_date` timestamp NULL DEFAULT (now()),
  `grace_period_at` timestamp NULL DEFAULT (now()),
  `expires_at` timestamp NULL DEFAULT (now()),
  `last_renewal_date` timestamp NULL DEFAULT (now()),
  `next_renewal_date` timestamp NULL DEFAULT (now()),
  `last_transaction_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_date` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_year` int GENERATED ALWAYS AS (year(`created_date`)) STORED NOT NULL,
  `updated_date` timestamp(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `last_transaction_uid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `next_product_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'The next product ID for case DOWNGRADE',
  PRIMARY KEY (`id`,`created_year`),
  KEY `idx_user_current_sub` (`user_id`,`is_current`,`order_id`),
  KEY `idx_status` (`status`),
  KEY `idx_purchase_platform` (`purchase_platform`),
  KEY `idx_expires_at` (`expires_at`),
  KEY `idx_platform_expired_purchases` (`purchase_platform`,`status`,`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
/*!50100 PARTITION BY RANGE (`created_year`)
(PARTITION p2024 VALUES LESS THAN (2025) ENGINE = InnoDB,
 PARTITION p2025 VALUES LESS THAN (2026) ENGINE = InnoDB,
 PARTITION p2026 VALUES LESS THAN (2027) ENGINE = InnoDB,
 PARTITION p2027 VALUES LESS THAN (2028) ENGINE = InnoDB,
 PARTITION p2028 VALUES LESS THAN (2029) ENGINE = InnoDB,
 PARTITION p2029 VALUES LESS THAN (2030) ENGINE = InnoDB,
 PARTITION p2030 VALUES LESS THAN (2031) ENGINE = InnoDB,
 PARTITION pmax VALUES LESS THAN MAXVALUE ENGINE = InnoDB) */