ALTER TABLE `setting`
ADD COLUMN `incoming_call` tinyint DEFAULT '1' AFTER `event_move_mail_noti`,
ADD COLUMN `incoming_mail` tinyint DEFAULT '1' AFTER `incoming_call`,
ADD COLUMN `filter_chat` tinyint DEFAULT '1' AFTER `incoming_mail`,
MODIFY COLUMN `default_cal` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `timezone` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT 'America/Chicago',
MODIFY COLUMN `tz_city` varchar(255) COLLATE utf8mb3_unicode_ci,
MODIFY COLUMN `calendar_color` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `folder_color` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `navbar_system` text COLLATE utf8mb3_unicode_ci NOT NULL,
MODIFY COLUMN `navbar_custom` text COLLATE utf8mb3_unicode_ci NOT NULL,
MODIFY COLUMN `infobox` text COLLATE utf8mb3_unicode_ci NOT NULL,
MODIFY COLUMN `from_email` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `avatar` mediumtext COLLATE utf8mb3_unicode_ci NOT NULL,
MODIFY COLUMN `recent_tz` text COLLATE utf8mb3_unicode_ci,
MODIFY COLUMN `order_url` mediumtext COLLATE utf8mb3_unicode_ci,
MODIFY COLUMN `order_todo` mediumtext COLLATE utf8mb3_unicode_ci,
MODIFY COLUMN `omni_cal_id` varchar(500) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `order_storyboard` mediumtext COLLATE utf8mb3_unicode_ci;