ALTER TABLE `third_party_account`
MODIFY COLUMN `server_income` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `user_income` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `pass_income` varchar(1000) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `port_income` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `server_smtp` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT '',
MODIFY COLUMN `user_smtp` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT '',
MODIFY COLUMN `pass_smtp` varchar(1000) COLLATE utf8mb3_unicode_ci DEFAULT '',
MODIFY COLUMN `port_smtp` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT '',
MODIFY COLUMN `server_caldav` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT '',
MODIFY COLUMN `server_path_caldav` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT '',
MODIFY COLUMN `port_caldav` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT '',
MODIFY COLUMN `auth_key` text COLLATE utf8mb3_unicode_ci,
MODIFY COLUMN `auth_token` text COLLATE utf8mb3_unicode_ci,
MODIFY COLUMN `refresh_token` text COLLATE utf8mb3_unicode_ci NOT NULL,
MODIFY COLUMN `provider` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT '',
MODIFY COLUMN `icloud_user_id` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `third_party_user_id` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `user_caldav` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `email_address` varchar(255) COLLATE utf8mb3_unicode_ci;