ALTER TABLE `user`
MODIFY COLUMN `username` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
MODIFY COLUMN `digesta1` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
MODIFY COLUMN `email` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL,
MODIFY COLUMN `password` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
MODIFY COLUMN `password2` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
MODIFY COLUMN `appreg_id` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `rsa` text COLLATE utf8mb3_unicode_ci NOT NULL,
MODIFY COLUMN `secondary_email` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `birthday` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `country` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `phone_number` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `country_code` varchar(25) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `token` varchar(500) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
MODIFY COLUMN `private_key_1` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
MODIFY COLUMN `private_key_2` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
MODIFY COLUMN `public_key` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
MODIFY COLUMN `digestb` varchar(255) COLLATE utf8mb3_unicode_ci;